name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push Docker images'
        required: false
        default: false
        type: boolean
      build_debian12_misskey:
        description: 'Build debian12-misskey'
        required: false
        default: false
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ fromJSON(github.event.inputs.push_images) }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push Docker image for debian12-misskey
        if: ${{ fromJSON(github.event.inputs.build_debian12_misskey) }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ fromJSON(github.event.inputs.push_images) }}
          tags: eric2369/debian12-misskey:${{ env.DATE }},eric2369/debian12-misskey:latest
          platforms: linux/amd64,linux/arm64
